SFO-9: Merge cambios en repositorio de Github
frank-martinez-iest/test-1 pull request #3
Opened 2020-11-13 05:02 UTC by nanyssalazar

Se agrega codigo a archivo.

2020-11-13 07:49 UTC, frank-martinez-iest requested changes
Muy buen 1er. intento 👍 🥇

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +       <nav class="barra">
Refactoriza el nav para que siga las buenas practicas que se enlistan en este articulo https://inclusive-components.design/menus-menu-buttons/

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +    <header></header>
header vacio?

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +            <a href="#">Pricing</a>
De preferencia maneja todos los strings o textos de tu app en minusculas y usa CSS text-transform cuando ocupes mostrar al usuario mayusculas o capitalizacion, etc...

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +        <section class="barra-imagen">
Quiza en mi diseño del ejercicio no se veia claro pero se supone que la seccion donde apareceria esto es un "Hero", puedes leer mas de esto aqui: https://www.developerdrive.com/full-page-hero-image-html-css/

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +    <nav class="navegacion">
esta seccion no es un nav component, solo es un listado, asi que puedes usar un "section" y un "ul" para cada elemento de esta parte

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +            <div class="main-content texto">
Este es un buen lugar para usar un "section" element

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +            <p>STACK:</p>
Aunque se vea pequeno el texto no deja de ser un encabezado de una seccion, asi que debe ser un Heading

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +            <ol>
Este puede ser un "ul" (UNordered List), el "ol" se usa para listas cuyo orden y enumeracion importan

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +                    <p>95%</p>
Como el porcentaje tiene una relacion con el texto que le precede, es semanticamente correcto que ambos textos sean parte del mismo PARAGRAPH. Modifica esto a que sea algo como `<p>React <span> 95% </span></p>`

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +    </div>
Problemas de indentacion

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +                <a href="#">Travel</a>
mismo comentario que hice para el nav debajo de tu header

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +        <div>
Este div esta de mas, puedes tener tus 2 nav elements dentro del footer sin necesidad de wrappearlos en divs

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +        <div>
mismo comentario de arriba, este div esta de mas

2020-11-13 07:49 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +                <div class="barra">
tambien este div esta de mas

2020-11-13 17:43 UTC, nanyssalazar commented on Andrea/exercise-1/index.html
> +    <header></header>
La etiqueta de cerrar se puso doble, lo corregiré.

2020-11-13 17:58 UTC, nanyssalazar commented on Andrea/exercise-1/index.html
> +            <p>THE AMAZING HUBBLE</p>
En este caso, lo puse como un <p> pero sería tambien un Heading? y si se ve mas pequeño que el siguiente, se puede tener un heading menor al que sigue? @frank-martinez-iest

2020-11-13 21:31 UTC, nanyssalazar commented
Ya corregí lo que me dijiste, crees que lo puedas checar de nuevo porfavor? @frank-martinez-iest

2020-11-14 08:05 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +            <p>THE AMAZING HUBBLE</p>
En este caso yo me iria por algo asi: 
```
<div class="titulo-col1">
            <p><span>THE AMAZING HUBBLE</span> spend less time coding</p>
```

2020-11-14 08:07 UTC, frank-martinez-iest commented on Andrea/exercise-1/index.html
> +            <p>THE AMAZING HUBBLE</p>
para lograr el salto de linea del span y que todas sean mayusculas (mediante css)  yo le pondria un class especifico al span y otro para el PARAGRAPH que engloba todo ese texto

2020-11-14 08:08 UTC, frank-martinez-iest reviewed
Esto esta mucho mejor!! Solo deje un comment pequeno

2020-11-14 19:54 UTC, nanyssalazar commented on Andrea/exercise-1/index.html
> +            <p>THE AMAZING HUBBLE</p>
Listo ya lo cambie. Gracias!

2020-11-14 19:55 UTC, nanyssalazar commented
> Esto esta mucho mejor!! Solo deje un comment pequeno

Ya hice el cambio que me marcaste:)

2020-11-18 06:57 UTC, frank-martinez-iest approved these changes
APPROVED

2020-11-18 06:57 UTC, merged